### PR TITLE
Update Freedesktop runtime to 23.08.

### PR DESCRIPTION
**Pull request by averms**
Haven't tested this locally so let's see if it passes CI.

### CODE REVIEW

**Comment by averms** [comment]
404...

**Comment by capfredf** [comment]
@flathubbot rebuild

**Comment by capfredf** [comment]
@averms can you push an empty change to trigger a rebuild?

**Comment by averms** [comment]
Try "bot, build". Otherwise I can push an empty commit 😅.

**Comment by capfredf** [comment]
@flathubbot bot, build

**Pull request merged**
